"""FR_01 — User Registration system tests.

28 test cases sourced from sheet FR_01 in ss_test_13.xlsx
(see data/FR_01_user_registration.csv).

Conventions:
  - All emails generated by tests use settings.TEST_EMAIL_PREFIX so the
    cleanup_test_users fixture wipes only test data, not real users.
  - OTPs are read straight from Redis (key "otp:<email>") via
    utils.otp_helper.wait_for_otp — no real mailbox needed.
"""
import time
import uuid

import pytest
from selenium.common.exceptions import NoAlertPresentException, UnexpectedAlertPresentException

from config import settings
from pages.register_page import RegisterPage
from utils.csv_reader import load_csv
from utils.db_helper import execute, fetch_one, find_user_by_email
from utils.otp_helper import wait_for_otp


# Lookup table: tc_id → row dict
CSV_ROWS = {r["tc_id"]: r for r in load_csv("FR_01_user_registration.csv")}


def _tc(tc_id):
    return CSV_ROWS[tc_id]


def _unique_email(domain="example.com"):
    return f"{settings.TEST_EMAIL_PREFIX}{uuid.uuid4().hex[:10]}@{domain}"


def _expected_msg(tc):
    """Prefer the parsed quoted message; fall back to the full expected text."""
    return tc["expected_messages"] or tc["expected"]


# =============================================================================
# Section 1 — UI/UX layout (FR_001_001 to FR_001_005)
# =============================================================================

class TestLayoutAndUI:
    def test_FR_001_001_layout_visible(self, driver):
        page = RegisterPage(driver).open()
        for name in page.INPUTS:
            assert page.field(name).is_displayed(), f"{name} not displayed"
        assert page.submit_button().is_displayed()

    def test_FR_001_002_all_five_fields_present(self, driver):
        page = RegisterPage(driver).open()
        for name in ("email", "fullName", "phone", "password", "confirmPassword"):
            assert page.field(name).is_displayed(), f"{name} field missing"

    def test_FR_001_003_placeholders(self, driver):
        page = RegisterPage(driver).open()
        # The sheet says SĐT placeholder = "0123456789" — code matches.
        assert page.placeholder("email") == "example@gmail.com"
        assert page.placeholder("fullName") == "Nguyễn Văn A"
        assert page.placeholder("phone") == "0123456789"
        assert page.placeholder("password") == "Tối thiểu 6 ký tự"
        assert page.placeholder("confirmPassword") == "Nhập lại mật khẩu"

    def test_FR_001_004_submit_button_and_login_link(self, driver):
        page = RegisterPage(driver).open()
        assert "Tiếp tục" in page.submit_text()
        link = driver.find_element(*page.LOGIN_LINK)
        assert link.is_displayed()
        assert link.get_attribute("href").endswith("/login")

    def test_FR_001_005_password_eye_toggle(self, driver):
        page = RegisterPage(driver).open()
        page.fill("password", "Abc123456")
        assert page.field_type("password") == "password"
        page.toggle_password()
        assert page.field_type("password") == "text"
        page.toggle_password()
        assert page.field_type("password") == "password"


# =============================================================================
# Section 2 — Register flow (FR_001_006 to FR_001_009)
# =============================================================================

class TestRegisterFlow:
    def test_FR_001_006_register_success(
        self, driver, db_conn, redis_conn, cleanup_test_users
    ):
        tc = _tc("FR_001_006")
        email = _unique_email()
        page = RegisterPage(driver).open()
        page.fill_form(
            email=email,
            fullName=tc["fullname"],
            phone=tc["phone"],
            password=tc["password"],
            confirmPassword=tc["confirm_password"],
        )
        page.click_submit()
        assert page.is_in_otp_step(), "Form did not transition to OTP step"

        otp = wait_for_otp(redis_conn, email, timeout=10)
        page.fill_otp(otp)
        page.click_verify()

        page.wait_for_url_contains("/login", timeout=15)
        assert "Đăng ký tài khoản" in driver.page_source

        user = find_user_by_email(db_conn, email)
        assert user is not None, "User row was not created"
        assert user["full_name"] == tc["fullname"]
        assert user["role"] == "STUDENT"
        assert user["status"] == "ACTIVE"
        assert user["password_hash"].startswith("$2"), "Password not bcrypt-hashed"
        assert user["password_hash"] != tc["password"]

    def test_FR_001_007_email_already_exists(
        self, driver, db_conn, redis_conn, cleanup_test_users
    ):
        tc = _tc("FR_001_007")
        email = _unique_email(domain="gmail.com")
        # Seed an existing user with the same email
        execute(
            db_conn,
            "INSERT INTO users (email, password_hash, full_name, role, status) "
            "VALUES (%s, %s, %s, %s, %s)",
            (email, "$2b$10$dummyhashforexistingusertest123456789012345678901234", "Existing", "STUDENT", "ACTIVE"),
        )

        page = RegisterPage(driver).open()
        page.fill_form(
            email=email,
            fullName=tc["fullname"],
            phone=tc["phone"],
            password=tc["password"],
            confirmPassword=tc["confirm_password"],
        )
        page.click_submit()
        # OTP request still goes through (backend doesn't pre-check uniqueness)
        assert page.is_in_otp_step()
        otp = wait_for_otp(redis_conn, email, timeout=10)
        page.fill_otp(otp)
        page.click_verify()

        # Backend rejects with 409 — message should surface in toast or inline
        time.sleep(2)
        assert "already exists" in driver.page_source.lower() or "tồn tại" in driver.page_source

        # DB still has only the seeded row, no duplicate
        rows = fetch_one(
            db_conn,
            "SELECT COUNT(*) AS c FROM users WHERE email = %s",
            (email,),
        )
        assert rows["c"] == 1

    def test_FR_001_008_empty_form_submit(self, driver):
        page = RegisterPage(driver).open()
        page.click_submit()
        # yup runs onSubmit, errors render synchronously; small buffer for paint
        time.sleep(0.5)
        assert page.field_error("email") == "Vui lòng nhập email"
        assert page.field_error("fullName") == "Họ và tên là bắt buộc"
        assert page.field_error("password") == "Vui lòng nhập mật khẩu"
        assert page.field_error("confirmPassword") == "Vui lòng nhập lại mật khẩu"

    def test_FR_001_009_submit_debounce(
        self, driver, db_conn, redis_conn, cleanup_test_users
    ):
        tc = _tc("FR_001_009")
        email = _unique_email()
        page = RegisterPage(driver).open()
        page.fill_form(
            email=email,
            fullName=tc["fullname"],
            phone=tc["phone"],
            password=tc["password"],
            confirmPassword=tc["confirm_password"],
        )
        page.rapid_click_submit(n=5)
        # If only one click made it through, the form will already be on the
        # OTP step (proof of debounce). Otherwise the submit button must be
        # disabled or its label must have switched to "Đang gửi OTP...".
        if page.is_in_otp_step(timeout=5):
            return
        assert page.submit_disabled() or page.submit_text() != "Tiếp tục", (
            "Submit button did not debounce after rapid clicks"
        )


# =============================================================================
# Section 3 — Email field validation (FR_001_010 to FR_001_014)
# =============================================================================

EMAIL_TC_IDS = ["FR_001_010", "FR_001_011", "FR_001_012", "FR_001_013", "FR_001_014"]


@pytest.mark.parametrize("tc_id", EMAIL_TC_IDS, ids=EMAIL_TC_IDS)
def test_email_field_validation(driver, tc_id):
    tc = _tc(tc_id)
    page = RegisterPage(driver).open()
    page.fill_and_blur("email", tc["email"])
    err = page.field_error("email")
    if tc["type"] == "Negative":
        expected = _expected_msg(tc)
        assert err is not None, f"Expected error '{expected}' but got none"
        assert expected in err, f"Expected '{expected}' in '{err}'"
    else:
        assert err is None, f"Unexpected error: {err}"


# =============================================================================
# Section 4 — Password field validation (FR_001_015 to FR_001_018)
# =============================================================================

class TestPasswordField:
    def test_FR_001_015_valid_password(self, driver):
        tc = _tc("FR_001_015")
        page = RegisterPage(driver).open()
        page.fill_and_blur("password", tc["password"])
        assert page.field_error("password") is None

    def test_FR_001_016_password_too_short(self, driver):
        tc = _tc("FR_001_016")
        page = RegisterPage(driver).open()
        page.fill_and_blur("password", tc["password"])
        err = page.field_error("password")
        assert err is not None
        assert _expected_msg(tc) in err

    def test_FR_001_017_password_empty(self, driver):
        tc = _tc("FR_001_017")
        page = RegisterPage(driver).open()
        page.fill_and_blur("password", "")
        err = page.field_error("password")
        assert err == "Vui lòng nhập mật khẩu"

    def test_FR_001_018_confirm_mismatch(self, driver):
        tc = _tc("FR_001_018")
        page = RegisterPage(driver).open()
        page.fill_and_blur("password", tc["password"])
        page.fill_and_blur("confirmPassword", tc["confirm_password"])
        err = page.field_error("confirmPassword")
        assert err is not None
        assert _expected_msg(tc) in err


# =============================================================================
# Section 5 — Full name field validation (FR_001_019 to FR_001_021)
# =============================================================================

FULLNAME_TC_IDS = ["FR_001_019", "FR_001_020", "FR_001_021"]


@pytest.mark.parametrize("tc_id", FULLNAME_TC_IDS, ids=FULLNAME_TC_IDS)
def test_fullname_field_validation(driver, tc_id):
    tc = _tc(tc_id)
    page = RegisterPage(driver).open()
    page.fill_and_blur("fullName", tc["fullname"])
    err = page.field_error("fullName")
    if tc["type"] == "Negative":
        expected = _expected_msg(tc)
        assert err is not None, f"Expected error '{expected}' but got none"
        assert expected in err
    else:
        assert err is None, f"Unexpected error: {err}"


# =============================================================================
# Section 6 — Phone field validation (FR_001_022 to FR_001_026)
# =============================================================================

PHONE_TC_IDS = ["FR_001_022", "FR_001_023", "FR_001_024", "FR_001_025", "FR_001_026"]


@pytest.mark.parametrize("tc_id", PHONE_TC_IDS, ids=PHONE_TC_IDS)
def test_phone_field_validation(driver, tc_id):
    tc = _tc(tc_id)
    page = RegisterPage(driver).open()
    page.fill_and_blur("phone", tc["phone"])
    err = page.field_error("phone")
    if tc["type"] == "Negative":
        expected = _expected_msg(tc)
        assert err is not None, f"Expected error '{expected}' but got none"
        assert expected in err
    else:
        assert err is None, f"Unexpected error: {err}"


# =============================================================================
# Section 7 — Security (FR_001_027 to FR_001_028)
# =============================================================================

class TestSecurity:
    def test_FR_001_027_xss_in_fullname(
        self, driver, db_conn, redis_conn, cleanup_test_users
    ):
        """Script in fullName must NOT execute as JS — React escapes by default."""
        tc = _tc("FR_001_027")
        email = _unique_email()
        page = RegisterPage(driver).open()
        page.fill_form(
            email=email,
            fullName=tc["fullname"],  # "<script>alert(1)</script>"
            phone="",
            password=tc["password"],
            confirmPassword=tc["password"],
        )
        page.click_submit()
        # No alert dialog should appear at any point
        time.sleep(1)
        try:
            alert = driver.switch_to.alert
            alert.dismiss()
            pytest.fail(f"XSS alert appeared: {alert.text}")
        except (NoAlertPresentException, UnexpectedAlertPresentException):
            pass

    def test_FR_001_028_sql_injection_email(self, driver):
        """' OR 1=1 -- in email must be rejected by the email validator."""
        tc = _tc("FR_001_028")
        page = RegisterPage(driver).open()
        page.fill_and_blur("email", tc["email"])
        err = page.field_error("email")
        assert err is not None, "Expected validation error for SQL-like email"
        assert "Email không hợp lệ" in err
