import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.scss";
import { ReactNode } from "react";
import ChatWidget from "@/components/chat/ChatWidget";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Elearning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="vi" className="text-sm md:text-base">
      <body
        className={`${beVietnamPro.className} antialiased leading-normal bg-white text-gray-900`}
      >
        {children}
        <ChatWidget />
        <Toaster position="top-right" />
        <div id="portal" />
      </body>
    </html>
  );
}
