[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --html=reports/html/index.html
    --self-contained-html
    --tb=short
    --color=yes
